### Get all persons
GET http://localhost:3002/api/persons
Content-Type: application/json;
### Get a person that exists (200)
GET http://localhost:3002/api/persons/6155224db7f5f94e58eb1517
Content-Type: application/json
### Get a person that doesn't exist (404)
GET http://localhost:3002/api/persons/99
Content-Type: application/json
### Delete a person (204)
DELETE http://localhost:3002/api/persons/2
Content-Type: application/json
### Delete a person that doesn't exist (400)
DELETE http://localhost:3002/api/persons/99
Content-Type: application/json
### Post a new person (201)
POST http://localhost:3002/api/persons
Content-Type: application/json

{
  "name": "Some Gy",
  "number": "234234234"
}
### Post a new person w/o name property
POST http://localhost:3002/api/persons
Content-Type: application/json

{
  "number": "23423423234"
}
### Post a new person w/o number property
POST http://localhost:3002/api/persons
Content-Type: application/json

{
  "name": "Missing number guy"
}
### Post a person who already exists (400)
POST http://localhost:3002/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "040-123456"
}